services:
  consul-server:
    image: consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -ui -node=consul-server -bootstrap-expect=1 -client=0.0.0.0"
